#!/bin/sh
# .husky/commit-msg

commit_msg_file=$1
pattern='^(feat|fix|docs|style|refactor|test|chore)(\([a-zA-Z0-9_-]+\))?: .+'
commit_msg=$(head -n1 "$commit_msg_file")

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "❌ Error: Commit message does not follow the expected format."
  echo "Please use the format: <type>(<scope>): <message>"
  echo "Example: feat(auth): add token validation"
  exit 1
fi

exit 0
