#!/bin/sh
# .husky/pre-push

cargo test -- --nocapture
if [ $? -ne 0 ]; then
    echo "❌ Some tests failed. Please fix them before pushing."
    exit 1
fi

echo "✅ All tests passed, proceeding with push..."
exit 0
